server: ../src/*.cpp ../../sauron-protocol/protocol.cpp ../../sauron-protocol/transport.cpp
	g++ ../src/*.cpp ../../sauron-protocol/protocol.cpp ../../sauron-protocol/transport.cpp -L/usr/lib -o server
